### ISSUE TITLE
Whenever I use "node main.js" nothing happens.

### ISSUE THREAD

**Issue by microscopicyt** [Aareksio/node-steam-card-farm#1]
The console just sits there for a while with just the cursor, and then it goes back to being able to put in more commands into root. Nothing about it working or whatever ,please help :(

Using node 6.9.1 and npm 3.10.8

**Comment by Aareksio** [comment]
Make sure your config file is correct. The app may not work correctly on nodejs v6. Once you check config file, I'd recommend using another software, like [ArchiSteamFarm](https://github.com/JustArchi/ArchiSteamFarm).

**Comment by microscopicyt** [comment]
Alright, I'll check it out :)

thanks for the response

**Comment by microscopicyt** [comment]
If you don't mind me asking, would you mind helping me set this up on a VPS? I'm confused by this lmao. If you are using ArchiSteamFarm.

**Comment by Aareksio** [comment]
Sorry. I'm not providing any help regarding ASF - please read the wiki of the project. Everything is explained step by step there.
