### ISSUE TITLE
No games to idle

### ISSUE THREAD

**Issue by woepertjes** [Aareksio/node-steam-card-farm#10]
I have it all running, it works nice and well on my dedicated bot accounts, however when i try to use it on one of my play accounts, it says there are no games to idle even though there are games that are still able to drop cards. Am i missing something?

**Comment by Aareksio** [comment]
The script uses https://steamcommunity.com/my/badges to load cards left to idle. It's looking for `\d+ card drops? remaining` - make sure your account language is set to english and such text is present on linked page.

**Comment by woepertjes** [comment]
ah, i changed my primary language to english and now it works. Cheers mate.
