### ISSUE TITLE
Disconnected from steam! Reason: 3

### ISSUE THREAD

**Issue by fran46** [Aareksio/node-steam-card-farm#2]
Hello! 
First of all, congratulations for your work!

The script works fine, but I usually receive this message:
"disconnected from steam! Reason: 3"

any ideas?
Do you have an updated version of the code?

Thanks

**Comment by Aareksio** [comment]
3 is No Connection.
Please use [ASF](https://github.com/JustArchi/ArchiSteamFarm).
