### ISSUE TITLE
!farmidle

### ISSUE THREAD

**Issue by woepertjes** [Aareksio/node-steam-card-farm#7]
I'm a lazy cow, not gonna lie about that. Script works really good, added some bits and bops here and there. managed to get email guard working with it very well. but for some odd reason when i do !farmidle (appid) it doesnt make all the bots idle that specific game. I'm a dumb cunt, also not gonna lie about that.

what do i do? :3

**Comment by Aareksio** [comment]
The bot needs to own said game.

**Comment by woepertjes** [comment]
it has said game.

**Comment by Aareksio** [comment]
Then maybe there's no cards left to idle. Judging from [L360](https://github.com/Aareksio/node-steam-card-farm/blob/master/main.js#L360) and [L366](https://github.com/Aareksio/node-steam-card-farm/blob/master/main.js#L366) games with no cards are skipped (and generally not parsed)

**Comment by woepertjes** [comment]
I've checked out both dota2 and Team fortress 2, both games got cards. but for some reason its not picking up that bot hgames got cards. Could it be possible that some games are idle proof?

**Comment by Aareksio** [comment]
You need to spend money in free games in order to unlock card drop.
