### ISSUE TITLE
 Where does the botid come from?

### ISSUE THREAD

**Issue by etilawol** [Aareksio/node-steam-card-farm#9]
I'm not very good at programming, but I'm trying to figure it out with an example of your script, tell me please how the value comes from bots[botid]? Thank you! Sorry for my bad english.

**Comment by Aareksio** [comment]
I don't really understand the question. If you're asking about values replaced with xxx in example - you need to dig them from your phone or desktop authenticator.

**Comment by etilawol** [comment]
Sorry it is very difficult for me to express my thoughts in the text
bots[ -> **botid** <- ].bot.redeemKey(key, function(result, details, apps) {
I asked about this value, how does it determine the bot?

**Comment by etilawol** [comment]
that is, when I run the function, the bot is assigned an id?

**Comment by Aareksio** [comment]
https://github.com/Aareksio/node-steam-card-farm/blob/master/main.js#L58

**Comment by etilawol** [comment]
I understand, thanks for the help.
